# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0004_auto_20170510_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='post_date',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='num_comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpost',
            name='post_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
