# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0005_auto_20170510_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geniuspost',
            name='last_comment_date',
        ),
        migrations.AddField(
            model_name='geniuspost',
            name='last_comment_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='geniuspost',
            name='num_comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
