# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0008_auto_20170510_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumchartrank',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='visualizations.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songchartrank',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='visualizations.Artist'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='albumchartrank',
            unique_together=set([]),
        ),
    ]
